// Static fallback + seed content for BrickPoint (also used when DB is empty)
export const IMG = {
  brickMason: "https://images.pexels.com/photos/19688828/pexels-photo-19688828.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  bricklayer: "https://images.pexels.com/photos/33603170/pexels-photo-33603170.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  wall: "https://images.pexels.com/photos/8961703/pexels-photo-8961703.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  site: "https://images.pexels.com/photos/38221540/pexels-photo-38221540.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  cables: "https://images.pexels.com/photos/8961695/pexels-photo-8961695.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  align: "https://images.pexels.com/photos/33194812/pexels-photo-33194812.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  kiln: "https://images.pexels.com/photos/35460203/pexels-photo-35460203.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  kilnWomen: "https://images.pexels.com/photos/8280818/pexels-photo-8280818.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  pile: "https://images.pexels.com/photos/15325569/pexels-photo-15325569.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  stacked: "https://images.pexels.com/photos/33160441/pexels-photo-33160441.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  redStack: "https://images.pexels.com/photos/34713630/pexels-photo-34713630.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  worker: "https://images.pexels.com/photos/34752732/pexels-photo-34752732.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  villa1: "https://images.pexels.com/photos/7031412/pexels-photo-7031412.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  villa2: "https://images.pexels.com/photos/8134847/pexels-photo-8134847.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  villa3: "https://images.pexels.com/photos/18894990/pexels-photo-18894990.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  apt: "https://images.pexels.com/photos/33414231/pexels-photo-33414231.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
};
export const VID = {
  hero: "https://videos.pexels.com/video-files/35411576/15003649_3840_2160_24fps.mp4",
  heroPoster: "https://images.pexels.com/videos/35411576/pexels-photo-35411576.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=630&w=1200",
  site: "https://videos.pexels.com/video-files/11355903/11355903-uhd_3840_2160_25fps.mp4",
  sitePoster: "https://images.pexels.com/videos/11355903/pexels-photo-11355903.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=630&w=1200",
  drone: "https://videos.pexels.com/video-files/27758012/12218981_3840_2160_25fps.mp4",
  dronePoster: "https://images.pexels.com/videos/27758012/aerial-bricks-clip-construction-27758012.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=630&w=1200",
  aerial: "https://videos.pexels.com/video-files/20731372/20731372-uhd_3840_2160_30fps.mp4",
  aerialPoster: "https://images.pexels.com/videos/20731372/aerial-build-building-buildings-20731372.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=630&w=1200",
};

export const PRODUCT_CATEGORIES_SEED = [
  { name: "Bricks", slug: "bricks", description: "Premium burnt-clay bricks for strong, durable masonry.", image: IMG.stacked, icon: "layers", sortOrder: 1 },
  { name: "SS7 Bricks", slug: "ss7-bricks", description: "Our flagship high-strength SS7 brick range.", image: IMG.redStack, icon: "award", sortOrder: 2 },
  { name: "Cement", slug: "cement", description: "Fresh, quality cement for every structural need.", image: IMG.site, icon: "package", sortOrder: 3 },
  { name: "Bajri / Crush", slug: "bajri-crush", description: "Graded crush and bajri for concrete and foundations.", image: IMG.pile, icon: "mountain", sortOrder: 4 },
  { name: "Sand / Rait", slug: "sand-rait", description: "Clean sand for masonry, plaster and concrete.", image: IMG.align, icon: "waves", sortOrder: 5 },
  { name: "Steel", slug: "steel", description: "Structural steel for reinforcement and framing.", image: IMG.site, icon: "anchor", sortOrder: 6 },
  { name: "Electric Conduit Pipes", slug: "electric-conduit-pipes", description: "Durable conduit pipes for safe electrical work.", image: IMG.cables, icon: "zap", sortOrder: 7 },
  { name: "Plumbing Pipes and Fittings", slug: "plumbing-pipes", description: "Reliable plumbing pipes and fittings.", image: IMG.wall, icon: "droplets", sortOrder: 8 },
  { name: "Construction Chemicals", slug: "construction-chemicals", description: "Waterproofing, bonding and repair chemicals.", image: IMG.brickMason, icon: "flask", sortOrder: 9 },
  { name: "Insulation and Membrane", slug: "insulation-membrane", description: "Heat and waterproofing insulation solutions.", image: IMG.villa1, icon: "shield", sortOrder: 10 },
  { name: "Cables and Wires", slug: "cables-wires", description: "Quality cables and wires for safe wiring.", image: IMG.cables, icon: "plug", sortOrder: 11 },
  { name: "Paints", slug: "paints", description: "Interior and exterior paints with lasting finish.", image: IMG.villa2, icon: "paintbrush", sortOrder: 12 },
  { name: "Lights", slug: "lights", description: "Modern lighting for homes and projects.", image: IMG.villa3, icon: "lightbulb", sortOrder: 13 },
  { name: "Switches and Sockets", slug: "switches-sockets", description: "Safe, premium switches and sockets.", image: IMG.cables, icon: "toggle", sortOrder: 14 },
  { name: "Other Construction Materials", slug: "other-materials", description: "Everything else your project needs.", image: IMG.bricklayer, icon: "boxes", sortOrder: 15 },
];

export const VIDEO_CATEGORIES_SEED = [
  { name: "SS7 Bricks", slug: "ss7-bricks", sortOrder: 1 },
  { name: "Brick Manufacturing", slug: "brick-manufacturing", sortOrder: 2 },
  { name: "Our Bhattas", slug: "our-bhattas", sortOrder: 3 },
  { name: "Brick Quality", slug: "brick-quality", sortOrder: 4 },
  { name: "Construction Projects", slug: "construction-projects", sortOrder: 5 },
  { name: "Construction Materials", slug: "construction-materials", sortOrder: 6 },
  { name: "Company / Brand", slug: "company-brand", sortOrder: 7 },
  { name: "Promotional Videos", slug: "promotional", sortOrder: 8 },
  { name: "Product Videos", slug: "product-videos", sortOrder: 9 },
  { name: "Behind the Scenes", slug: "behind-the-scenes", sortOrder: 10 },
  { name: "Other Videos", slug: "other-videos", sortOrder: 11 },
];

export const LOCATIONS_SEED = [
  {
    name: "Masha Allah Bricks Company — Ram Thaman",
    slug: "masha-allah-ram-thaman",
    address: "Ram Thaman, Punjab, Pakistan",
    description: "Main brick manufacturing unit producing quality burnt-clay bricks with consistent firing and strength.",
    image: IMG.kiln,
    mapsUrl: "https://maps.app.goo.gl/6Pi5BNTsxPRkn1cn7?g_st=awb",
    phone: "0315 2850818",
    hours: "Mon – Sat: 8:00 AM – 6:00 PM",
    sortOrder: 1,
  },
  {
    name: "Fine Bricks Company — Raja Jang",
    slug: "fine-bricks-raja-jang",
    address: "Raja Jang, Punjab, Pakistan",
    description: "Fine Bricks production facility focused on dimensional accuracy and premium finish bricks.",
    image: IMG.kilnWomen,
    mapsUrl: "https://maps.app.goo.gl/SDaxqVM55qXt66wW8?g_st=awb",
    phone: "0315 2850818",
    hours: "Mon – Sat: 8:00 AM – 6:00 PM",
    sortOrder: 2,
  },
  {
    name: "Masha Allah Bricks Company — Sattoki",
    slug: "masha-allah-sattoki",
    address: "Sattoki, Punjab, Pakistan",
    description: "High-capacity bhatta supporting bulk orders for contractors and large developments.",
    image: IMG.pile,
    mapsUrl: "https://google.com/maps?q=31.2328,74.3169424&z=17&hl=en",
    phone: "0315 2850818",
    hours: "Mon – Sat: 8:00 AM – 6:00 PM",
    sortOrder: 3,
  },
  {
    name: "BrickPoint — Head Office",
    slug: "brickpoint-office",
    address: "Lahore, Punjab, Pakistan",
    description: "Sales office for quotations, coordination and customer support. Contact us for bulk supply and project planning.",
    image: IMG.villa1,
    mapsUrl: "https://maps.app.goo.gl/GACXw15YxyV4bK5t8?g_st=awb",
    phone: "0315 2850818",
    hours: "Mon – Sat: 9:00 AM – 7:00 PM",
    sortOrder: 4,
  },
];
