<?php
/**
 * BrickPoint Complete Seed / Demo Data Catalog
 *
 * Sourced directly from Next.js seed database and pages.
 *
 * @package BrickPoint
 */

if ( ! defined( 'ABSPATH' ) ) {
  exit;
}

function brickpoint_get_demo_data() {
  return array(
    'categories' => array(
      array(
        'name'        => 'SS7 Bricks',
        'slug'        => 'ss7-bricks',
        'description' => 'Premium high-density burnt clay bricks engineered for strength, uniform shape and durability.',
        'image'       => 'red-stack.png',
        'order'       => 1,
      ),
      array(
        'name'        => 'First Class Bricks (Awwal)',
        'slug'        => 'first-class-bricks',
        'description' => 'Top-grade fired clay bricks with sharp edges, uniform red coloration and superior load resistance.',
        'image'       => 'stacked.png',
        'order'       => 2,
      ),
      array(
        'name'        => 'Second Class Bricks (Doyam)',
        'slug'        => 'second-class-bricks',
        'description' => 'Economical construction bricks ideal for inner partitions, boundary walls, and foundation work.',
        'image'       => 'pile.png',
        'order'       => 3,
      ),
      array(
        'name'        => 'Cement',
        'slug'        => 'cement',
        'description' => 'Premium Ordinary Portland and Sulphate Resistant cement from certified national manufacturers.',
        'image'       => 'wall.png',
        'order'       => 4,
      ),
      array(
        'name'        => 'Crush / Aggregates (Bajri)',
        'slug'        => 'crush-bajri',
        'description' => 'Washed Margalla and Sargodha crushed aggregates in 1/2 inch and 3/4 inch sizes for structural concrete.',
        'image'       => 'site.png',
        'order'       => 5,
      ),
      array(
        'name'        => 'Sand (Rait)',
        'slug'        => 'sand-rait',
        'description' => 'Screened Chenab and Ravi sand graded specifically for masonry, plastering, and RCC concrete casting.',
        'image'       => 'worker.png',
        'order'       => 6,
      ),
      array(
        'name'        => 'Deformed Steel Bars (Sarya)',
        'slug'        => 'steel-sarya',
        'description' => 'Grade 60 and Grade 40 ribbed high-yield deformed bars adhering to ASTM A615 standards.',
        'image'       => 'site.png',
        'order'       => 7,
      ),
      array(
        'name'        => 'Pipes & Fittings',
        'slug'        => 'pipes-fittings',
        'description' => 'High-performance UPVC, PPRC and CPVC piping systems for internal and external plumbing.',
        'image'       => 'cables.png',
        'order'       => 8,
      ),
      array(
        'name'        => 'Cables & Electrical',
        'slug'        => 'cables-electrical',
        'description' => '99.9% pure copper electrical wiring, conduit pipes, switchboards and distribution boxes.',
        'image'       => 'cables.png',
        'order'       => 9,
      ),
      array(
        'name'        => 'Construction Chemicals',
        'slug'        => 'construction-chemicals',
        'description' => 'Waterproofing admixtures, bonding agents, damp-proofing coatings and concrete plasticizers.',
        'image'       => 'wall.png',
        'order'       => 10,
      ),
      array(
        'name'        => 'Paints & Finishes',
        'slug'        => 'paints-finishes',
        'description' => 'Weather-shield exterior emulsions, interior wall coatings, primers, sealers and rock wall finishes.',
        'image'       => 'align.png',
        'order'       => 11,
      ),
      array(
        'name'        => 'LED Lights & Fixtures',
        'slug'        => 'led-lights',
        'description' => 'Energy efficient recessed SMD spotlights, panel lights, flood lights and commercial architectural illumination.',
        'image'       => 'cables.png',
        'order'       => 12,
      ),
    ),

    'products' => array(
      array(
        'title'        => 'SS7 Premium Red Bricks',
        'slug'         => 'ss7-premium-red-bricks',
        'category'     => 'SS7 Bricks',
        'price'        => 'Rs 14,000',
        'price_label'  => 'per 1,000 bricks',
        'unit'         => '1000 Bricks',
        'availability' => 'In Stock',
        'badge'        => 'Flagship Product',
        'featured'     => '1',
        'sku'          => 'BP-SS7-01',
        'image'        => 'red-stack.png',
        'short'        => 'Our flagship SS7 burnt clay bricks engineered for high structural strength, sharp edges, and uniform dimensions.',
        'specs'        => "Size: 9\" x 4.5\" x 3\"\nClay Type: Selected Alluvial Clay\nFiring: High Temperature Continuous Kiln\nWater Absorption: < 15%\nCrushing Strength: > 2000 PSI",
        'features'     => "Uniform rich red coloration\nSharp rectangular edges for tight mortar joints\nRinging metallic bell sound on impact\nIdeal for load-bearing walls and multi-storey structures",
        'video'        => 'https://videos.pexels.com/video-files/35411576/15003649_3840_2160_24fps.mp4',
        'content'      => 'SS7 Bricks are the benchmark of brick quality across Lahore and Punjab. Produced at our specialized kiln units under rigorous temperature controls, each batch is thoroughly cured and quality-tested before dispatch. Whether building a luxury residence in DHA or a commercial plaza, SS7 ensures lasting integrity.',
      ),
      array(
        'title'        => 'First Class Red Bricks (Awwal)',
        'slug'         => 'first-class-red-bricks-awwal',
        'category'     => 'First Class Bricks (Awwal)',
        'price'        => 'Rs 13,000',
        'price_label'  => 'per 1,000 bricks',
        'unit'         => '1000 Bricks',
        'availability' => 'In Stock',
        'badge'        => 'Popular Choice',
        'featured'     => '1',
        'sku'          => 'BP-AWW-02',
        'image'        => 'stacked.png',
        'short'        => 'Standard Awwal quality burnt clay bricks. Uniformly fired with clean edges and dependable structural capacity.',
        'specs'        => "Size: 9\" x 4.5\" x 3\"\nGrade: First Class (Awwal)\nFiring: Coal Kiln Fired\nWater Absorption: < 18%",
        'features'     => "Clean surfaces\nStandard size compliance\nStrong mortar adherence\nReadily available in high volume",
        'content'      => 'First Class (Awwal) bricks represent the most trusted standard in residential and commercial brickwork across Pakistan. Carefully sorted at the kiln face, these bricks guarantee uniform wall lines and minimal mortar wastage.',
      ),
      array(
        'title'        => 'Second Class Bricks (Doyam)',
        'slug'         => 'second-class-bricks-doyam',
        'category'     => 'Second Class Bricks (Doyam)',
        'price'        => 'Rs 10,500',
        'price_label'  => 'per 1,000 bricks',
        'unit'         => '1000 Bricks',
        'availability' => 'In Stock',
        'badge'        => 'Economy',
        'featured'     => '0',
        'sku'          => 'BP-DOY-03',
        'image'        => 'pile.png',
        'short'        => 'Cost-effective Doyam bricks for foundation footings, boundary walls, internal partition walls, and non-load-bearing enclosures.',
        'specs'        => "Size: 9\" x 4.5\" x 3\"\nGrade: Second Class (Doyam)\nWater Absorption: < 22%",
        'features'     => "Economical rate for bulk applications\nGood compressive strength\nSuitable for plastered masonry",
        'content'      => 'Second Class (Doyam) bricks provide substantial cost savings for areas where bricks will be completely concealed or plastered over. Ideal for foundation masonry, boundary walls, and temporary site structures.',
      ),
      array(
        'title'        => 'Falcon / Maple Leaf Portland Cement',
        'slug'         => 'portland-cement-50kg',
        'category'     => 'Cement',
        'price'        => 'Rs 1,450',
        'price_label'  => 'per 50 kg bag',
        'unit'         => '50 kg Bag',
        'availability' => 'In Stock',
        'badge'        => 'Certified Grade',
        'featured'     => '1',
        'sku'          => 'BP-CEM-04',
        'image'        => 'wall.png',
        'short'        => 'High early strength Ordinary Portland Cement (OPC) 53/43 Grade, fresh supply directly from factory distribution depots.',
        'specs'        => "Weight: 50 kg\nType: Ordinary Portland Cement\nPackaging: 3-Ply Moisture Resistant Paper Bag\nCompliance: PS 232 / ASTM C150",
        'features'     => "Rapid setting time\nHigh early compressive strength\nLow heat of hydration\nConsistent batch freshness",
        'content'      => 'We supply fresh, factory-direct cement bags suitable for all structural reinforced concrete work (RCC), slabs, columns, beams, brick masonry mortar, and plaster.',
      ),
      array(
        'title'        => 'Margalla Crushed Stone / Bajri (1/2")',
        'slug'         => 'margalla-crush-bajri-half-inch',
        'category'     => 'Crush / Aggregates (Bajri)',
        'price'        => 'Rs 115',
        'price_label'  => 'per cubic foot (cft)',
        'unit'         => 'CFT',
        'availability' => 'In Stock',
        'badge'        => 'Washed Margalla',
        'featured'     => '1',
        'sku'          => 'BP-CRU-05',
        'image'        => 'site.png',
        'short'        => 'Washed, machine-crushed Margalla limestone aggregates in 1/2 inch nominal size, zero dust content.',
        'specs'        => "Nominal Size: 1/2 inch (12mm)\nOrigin: Margalla Hills Quarries\nType: Blue-Grey Limestone\nCleanliness: Double Washed, Low Fines",
        'features'     => "Cubical particle shape for optimal compaction\nHigh aggregate crushing value\nZero organic matter or mud",
        'content'      => 'Essential for high-strength RCC slabs, columns, and pre-cast concrete elements. Delivered in dumpers and mini-trucks right to your site.',
      ),
      array(
        'title'        => 'Chenab River Sand (Rait)',
        'slug'         => 'chenab-river-sand-cft',
        'category'     => 'Sand (Rait)',
        'price'        => 'Rs 58',
        'price_label'  => 'per cubic foot (cft)',
        'unit'         => 'CFT',
        'availability' => 'In Stock',
        'badge'        => 'Screened River Sand',
        'featured'     => '1',
        'sku'          => 'BP-SND-06',
        'image'        => 'worker.png',
        'short'        => 'Screened Chenab coarse sand with optimal fineness modulus for structural concrete and high-strength mortar.',
        'specs'        => "Fineness Modulus: 2.3 - 2.8\nOrigin: Chenab River Basin\nScreening: Clean, Coarse Graded",
        'features'     => "Optimal grading curve for concrete packing\nFree from silt, clay lumps and organic debris\nEnhances concrete compressive strength",
        'content'      => 'Chenab sand is prized among Pakistan contractors for casting heavy concrete slabs and load-bearing structures due to its angular coarse grains.',
      ),
      array(
        'title'        => 'Grade 60 Deformed Steel Rebar (Sarya)',
        'slug'         => 'grade-60-steel-rebar-ton',
        'category'     => 'Deformed Steel Bars (Sarya)',
        'price'        => 'Rs 255,000',
        'price_label'  => 'per metric ton',
        'unit'         => 'Ton',
        'availability' => 'In Stock',
        'badge'        => 'ASTM A615 Grade 60',
        'featured'     => '1',
        'sku'          => 'BP-STL-07',
        'image'        => 'site.png',
        'short'        => 'Thermo-Mechanically Treated (TMT) Grade 60 high-yield deformed steel rebar in 3/8", 1/2", 5/8", 3/4" and 1" diameters.',
        'specs'        => "Standard: ASTM A615 Grade 60\nYield Strength: Minimum 60,000 PSI (415 MPa)\nLength: Standard 40 ft bars\nDiameters: 3/8\" to 1\"",
        'features'     => "Superior rib geometry for strong concrete bond\nHigh ductility and earthquake resistance\nEasy cold bending on site",
        'content'      => 'Certified mill test certificates provided with every consignment. Available in bundle lots or metric ton weights with direct crane-offloading assistance.',
      ),
      array(
        'title'        => 'UPVC Sewerage & Drainage Pipes (4")',
        'slug'         => 'upvc-sewerage-pipes-4-inch',
        'category'     => 'Pipes & Fittings',
        'price'        => 'Rs 2,850',
        'price_label'  => 'per 13 ft pipe length',
        'unit'         => '13 ft Length',
        'availability' => 'In Stock',
        'badge'        => 'Class B / C',
        'featured'     => '0',
        'sku'          => 'BP-PIP-08',
        'image'        => 'cables.png',
        'short'        => 'Heavy-duty 4-inch UPVC drainage and sewerage pipes with rubber-ring sockets for watertight domestic and commercial waste lines.',
        'specs'        => "Diameter: 4 inches (110mm)\nStandard: BS 3505 / PS 3051\nJointing: Rubber Ring Socket / Solvent Cement",
        'features'     => "Corrosion proof and chemical resistant\nSmooth bore prevents blockages\nLong underground service life (50+ years)",
        'content'      => 'Engineered for building drainage, rain-water drainage and external sewerage lines. Complete range of elbows, tees, clean-outs and traps available.',
      ),
      array(
        'title'        => 'Pakistan Cables 7/.029 Pure Copper Cable',
        'slug'         => 'pakistan-cables-7-029-copper',
        'category'     => 'Cables & Electrical',
        'price'        => 'Rs 18,200',
        'price_label'  => 'per 90-meter coil',
        'unit'         => '90m Coil',
        'availability' => 'In Stock',
        'badge'        => '99.9% Pure Copper',
        'featured'     => '1',
        'sku'          => 'BP-ELE-09',
        'image'        => 'cables.png',
        'short'        => 'Authentic 7/.029 single core PVC insulated wiring cable made from 99.9% electrolytic grade copper.',
        'specs'        => "Conductor: 99.9% Pure Copper\nSize: 7/.029 (2.5mm² equivalent)\nLength: 90 meters (100 yards)\nVoltage: 450/750V",
        'features'     => "Flame retardant grade PVC insulation\nGuaranteed strand count and gauge\nPrevents voltage drops and overheating",
        'content'      => 'Guaranteed 100% genuine cable coils with verification scratch codes. Used for power plug circuits, light points, AC circuits and distribution panels.',
      ),
      array(
        'title'        => 'Sika / MasterSeal SBR Waterproofing Chemical',
        'slug'         => 'sbr-waterproofing-bonding-agent-20l',
        'category'     => 'Construction Chemicals',
        'price'        => 'Rs 9,500',
        'price_label'  => 'per 20-litre container',
        'unit'         => '20 Litre Can',
        'availability' => 'In Stock',
        'badge'        => 'Waterproof Shield',
        'featured'     => '0',
        'sku'          => 'BP-CHM-10',
        'image'        => 'wall.png',
        'short'        => 'Styrene-butadiene rubber (SBR) polymer emulsion for concrete repair, basement damp-proofing, and water-retaining structures.',
        'specs'        => "Base: SBR Polymer Emulsion\nVolume: 20 Litres\nDosage: 5 - 10% by cement weight\nApplication: Roofs, Basements, Bathrooms",
        'features'     => "Permanently stops water seepage and efflorescence\nImproves mortar tensile & flexural strength\nExcellent bonding on old-to-new concrete",
        'content'      => 'Essential chemical admixture for roof screeds, water tanks, foundation damp-proof course (DPC), and tiled bathroom membranes.',
      ),
      array(
        'title'        => 'Berger WeatherCoat Exterior Shield Paint',
        'slug'         => 'weathercoat-exterior-paint-16l',
        'category'     => 'Paints & Finishes',
        'price'        => 'Rs 16,800',
        'price_label'  => 'per 16-litre drum',
        'unit'         => '16 Litre Drum',
        'availability' => 'In Stock',
        'badge'        => 'Anti-Fungal Protection',
        'featured'     => '0',
        'sku'          => 'BP-PNT-11',
        'image'        => 'align.png',
        'short'        => 'Premium 100% pure acrylic exterior emulsion with silicone additives providing all-weather protection against heat, UV and rain.',
        'specs'        => "Finish: Low Sheen Smooth Acrylic\nVolume: 16 Litres\nCoverage: 120 - 140 sq ft / litre / coat\nWarranty: 5 Year Exterior Protection",
        'features'     => "Repels dirt, dust and fungal stains\nResists intense sunlight and heavy monsoon rain\nWide palette of modern architectural shades",
        'content'      => 'Protect your building exterior facade from moisture and sun discoloration. Applied over exterior primer on masonry, brickwork and concrete.',
      ),
      array(
        'title'        => '12W Recessed Architectural LED SMD Light',
        'slug'         => '12w-recessed-architectural-led-smd',
        'category'     => 'LED Lights & Fixtures',
        'price'        => 'Rs 650',
        'price_label'  => 'per unit with driver',
        'unit'         => 'Piece',
        'availability' => 'In Stock',
        'badge'        => 'Die-Cast Aluminum',
        'featured'     => '0',
        'sku'          => 'BP-LGT-12',
        'image'        => 'cables.png',
        'short'        => 'Die-cast aluminum housing 12-watt recessed ceiling downlight with high-CRI Bridgelux LED chip and isolated surge-protected driver.',
        'specs'        => "Wattage: 12W (1100 Lumens)\nColor Temp: 3000K Warm / 4000K Natural / 6500K Cool\nCutout: 3.5 inches\nLifespan: 30,000 Hours",
        'features'     => "Heavy die-cast heat sink for longevity\nGlare-free frosted diffuser lens\nSurge protected constant current driver",
        'content'      => 'Perfect for false ceilings in living rooms, bedrooms, kitchens, retail stores, and commercial office interiors. Low power consumption and minimal heat.',
      ),
    ),

    'videos' => array(
      array(
        'title'       => 'Inside BrickPoint — Automated Firing & Continuous Kiln Operations',
        'slug'        => 'automated-firing-continuous-kiln-operations',
        'category'    => 'Manufacturing',
        'source'      => 'mp4',
        'url'         => 'https://videos.pexels.com/video-files/27758012/12218981_3840_2160_25fps.mp4',
        'duration'    => '1:45',
        'featured'    => '1',
        'image'       => 'drone-poster.png',
        'description' => 'A behind-the-scenes aerial and ground walkthrough of our brick manufacturing plant, clay mixing pits, and continuous coal-firing chambers.',
      ),
      array(
        'title'       => 'From the Bhatta to Your Building — Brick Selection & Firing',
        'slug'        => 'from-the-bhatta-to-your-building',
        'category'    => 'Quality Checks',
        'source'      => 'mp4',
        'url'         => 'https://videos.pexels.com/video-files/11355903/11355903-uhd_3840_2160_25fps.mp4',
        'duration'    => '2:10',
        'featured'    => '0',
        'image'       => 'site-poster.png',
        'description' => 'See how our seasoned technicians inspect brick dimensions, ringing sounds, color saturation, and load resistance before approval.',
      ),
      array(
        'title'       => 'Materials That Become Landmarks — Site Construction Overview',
        'slug'        => 'materials-that-become-landmarks',
        'category'    => 'Projects',
        'source'      => 'mp4',
        'url'         => 'https://videos.pexels.com/video-files/20731372/20731372-uhd_3840_2160_30fps.mp4',
        'duration'    => '1:30',
        'featured'    => '0',
        'image'       => 'aerial-poster.png',
        'description' => 'Aerial perspective of multi-unit residential developments utilizing BrickPoint SS7 bricks and structural aggregates.',
      ),
      array(
        'title'       => 'SS7 Brick Firing Process & Clay Selection',
        'slug'        => 'ss7-brick-firing-process',
        'category'    => 'Manufacturing',
        'source'      => 'mp4',
        'url'         => 'https://videos.pexels.com/video-files/35411576/15003649_3840_2160_24fps.mp4',
        'duration'    => '2:40',
        'featured'    => '0',
        'image'       => 'hero-poster.png',
        'description' => 'Discover how SS7 bricks achieve their renowned density through selected clay preparation, uniform hydraulic pressing, and controlled baking.',
      ),
      array(
        'title'       => 'On-Site Quality Testing: Water Absorption & Bell Sound Ring Test',
        'slug'        => 'on-site-brick-quality-testing',
        'category'    => 'Quality Checks',
        'source'      => 'mp4',
        'url'         => 'https://videos.pexels.com/video-files/11355903/11355903-uhd_3840_2160_25fps.mp4',
        'duration'    => '1:15',
        'featured'    => '0',
        'image'       => 'site-poster.png',
        'description' => 'Simple field tests every contractor and home builder should know to differentiate First-Class Awwal bricks from substandard batches.',
      ),
      array(
        'title'       => 'Large Scale Material Logistics & Bhatta Truck Loading',
        'slug'        => 'large-scale-material-logistics',
        'category'    => 'Operations',
        'source'      => 'mp4',
        'url'         => 'https://videos.pexels.com/video-files/27758012/12218981_3840_2160_25fps.mp4',
        'duration'    => '1:55',
        'featured'    => '0',
        'image'       => 'drone-poster.png',
        'description' => 'Careful manual and mechanized stacking into open-bed trucks ensuring zero breakage during transport across Punjab highways.',
      ),
    ),

    'projects' => array(
      array(
        'title'       => 'DHA Lahore Phase 6 — Luxury Villa Reference',
        'slug'        => 'dha-lahore-phase-6-luxury-villa',
        'category'    => 'Residential',
        'location'    => 'DHA Lahore',
        'status'      => 'Illustrative construction reference',
        'image'       => 'villa1.png',
        'description' => 'A showcase of modern architectural masonry combining exposed SS7 fair-face brickwork with structural concrete and custom metal cladding.',
      ),
      array(
        'title'       => 'Bahria Town Lahore — Contemporary Residence Reference',
        'slug'        => 'bahria-town-lahore-contemporary-residence',
        'category'    => 'Residential',
        'location'    => 'Bahria Town Lahore',
        'status'      => 'Illustrative construction reference',
        'image'       => 'villa2.png',
        'description' => 'Multi-storey private residence highlighting thermal mass efficiency achieved through double-leaf brick exterior walling.',
      ),
      array(
        'title'       => 'Lake City Lahore — Private Estate Reference',
        'slug'        => 'lake-city-lahore-private-estate',
        'category'    => 'Residential',
        'location'    => 'Lake City Lahore',
        'status'      => 'Illustrative construction reference',
        'image'       => 'villa3.png',
        'description' => 'Sprawling contemporary estate built with high-density structural clay bricks, high-spec waterproofing chemicals, and grade 60 steel.',
      ),
      array(
        'title'       => 'LDA City Lahore — Commercial Plaza Development Reference',
        'slug'        => 'lda-city-lahore-commercial-plaza',
        'category'    => 'Commercial',
        'location'    => 'LDA City Lahore',
        'status'      => 'Illustrative construction reference',
        'image'       => 'apt.png',
        'description' => 'Five-floor commercial mixed-use project utilizing bulk supply of first-class bricks, Margalla crushed aggregate, and certified cement.',
      ),
      array(
        'title'       => 'Etihad Town — Gated Community Housing Block Reference',
        'slug'        => 'etihad-town-housing-block',
        'category'    => 'Community',
        'location'    => 'Etihad Town Lahore',
        'status'      => 'Illustrative construction reference',
        'image'       => 'site.png',
        'description' => 'Systematic bulk material staging and phased brick deliveries supporting rapid multi-home residential developments.',
      ),
      array(
        'title'       => 'Al-Kabir Town — Multi-Storey Apartment Structure Reference',
        'slug'        => 'al-kabir-town-apartment-structure',
        'category'    => 'Residential High-Rise',
        'location'    => 'Al-Kabir Town Lahore',
        'status'      => 'Illustrative construction reference',
        'image'       => 'cables.png',
        'description' => 'Structural frame and infill masonry reference demonstrating coordinated electrical conduits, plumbing shafts, and brick partition walls.',
      ),
    ),

    'locations' => array(
      array(
        'title'       => 'Masha Allah Bricks Company (Bhatta Unit 1)',
        'slug'        => 'masha-allah-bricks-company-unit-1',
        'address'     => 'Depalpur Road, Okara District, Punjab, Pakistan',
        'phone'       => '0315 2850818',
        'hours'       => 'Mon – Sat: 7:00 AM – 6:30 PM',
        'maps_url'    => 'https://maps.google.com/?q=Depalpur+Road+Okara+Pakistan',
        'video'       => 'https://videos.pexels.com/video-files/27758012/12218981_3840_2160_25fps.mp4',
        'image'       => 'kiln.png',
        'description' => 'Our flagship production facility featuring continuous high-draft kiln chambers, dedicated clay conditioning beds, and fleet dispatch yards.',
      ),
      array(
        'title'       => 'Fine Bricks Company (Bhatta Unit 2)',
        'slug'        => 'fine-bricks-company-unit-2',
        'address'     => 'Multan Road Bypass, Sahiwal / Okara Region, Punjab, Pakistan',
        'phone'       => '0315 2850818',
        'hours'       => 'Mon – Sat: 7:30 AM – 6:00 PM',
        'maps_url'    => 'https://maps.google.com/?q=Multan+Road+Punjab+Pakistan',
        'video'       => 'https://videos.pexels.com/video-files/11355903/11355903-uhd_3840_2160_25fps.mp4',
        'image'       => 'kiln-women.png',
        'description' => 'Specialized in first-class Awwal standard bricks and specialized mould shapes, servicing regional commercial contractors with high daily volume.',
      ),
      array(
        'title'       => 'SS7 Bricks Manufacturing Facility (Unit 3)',
        'slug'        => 'ss7-bricks-manufacturing-facility-unit-3',
        'address'     => 'Grand Trunk Road / Regional Kiln Cluster, Punjab, Pakistan',
        'phone'       => '0315 2850818',
        'hours'       => 'Mon – Sat: 8:00 AM – 6:00 PM',
        'maps_url'    => 'https://maps.google.com/?q=Lahore+Punjab+Pakistan',
        'video'       => 'https://videos.pexels.com/video-files/35411576/15003649_3840_2160_24fps.mp4',
        'image'       => 'red-stack.png',
        'description' => 'Exclusive production line dedicated to high-density, sharp-cornered SS7 red bricks for Lahore high-end architectural and structural builds.',
      ),
      array(
        'title'       => 'BrickPoint Head Office & Coordination Hub',
        'slug'        => 'brickpoint-head-office-lahore',
        'address'     => 'Commercial Zone, DHA / Ring Road Interchange, Lahore, Punjab, Pakistan',
        'phone'       => '0315 2850818',
        'hours'       => 'Mon – Sat: 9:00 AM – 7:00 PM',
        'maps_url'    => 'https://maps.google.com/?q=DHA+Lahore+Pakistan',
        'video'       => 'https://videos.pexels.com/video-files/20731372/20731372-uhd_3840_2160_30fps.mp4',
        'image'       => 'site.png',
        'description' => 'Head corporate office managing builder procurement contracts, material testing documentation, WhatsApp order coordination, and logistics.',
      ),
    ),

    'posts' => array(
      array(
        'title'       => 'How to Identify First Class Awwal Bricks on Site: Field Guide',
        'slug'        => 'how-to-identify-first-class-awwal-bricks',
        'category'    => 'Quality Guides',
        'tags'        => 'Bricks, Quality, Inspection, Construction',
        'image'       => 'brick-mason.png',
        'excerpt'     => 'A comprehensive practical checklist for contractors and architects to verify brick quality directly at delivery before unloading.',
        'content'     => 'When trucks arrive at your construction site, checking brick quality takes less than five minutes if you know what to look for. 1. The Ringing Sound: Strike two bricks firmly against one another. First-class bricks produce a clear, ringing metallic tone. A dull thud signals porous or under-baked clay. 2. Edge Sharpness: Ensure edges are crisp and straight with no excessive crumbling. 3. Water Absorption: Soak a test sample in water for 24 hours — high quality bricks absorb less than 15% of their dry weight. 4. Dimensions: Verify standard 9" x 4.5" x 3" measurements to avoid irregular mortar lines.',
      ),
      array(
        'title'       => 'Complete Material Estimation Checklist for a 1-Kanal House in Lahore',
        'slug'        => 'complete-material-estimation-checklist-1-kanal-house',
        'category'    => 'Planning & Estimation',
        'tags'        => 'Costing, Estimation, 1 Kanal, Lahore',
        'image'       => 'site.png',
        'excerpt'     => 'Accurate quantity budgeting for grey structure construction: bricks, cement bags, Margalla crush, Chenab sand, and Grade 60 steel.',
        'content'     => 'Constructing a standard double-storey 1-Kanal residence (covered area roughly 5,000 to 5,500 sq ft) requires careful grey-structure procurement. Approximate quantities: Bricks: 90,000 to 110,000 bricks depending on wall thicknesses. Cement: 1,400 to 1,600 bags. Steel (Grade 60): 18 to 22 tons. Margalla Crush (1/2" & 3/4"): 5,000 to 6,000 cubic feet. Chenab Sand: 6,000 to 7,500 cubic feet. Contact BrickPoint on WhatsApp to get project pricing and scheduled staged deliveries.',
      ),
      array(
        'title'       => 'Why Mortar Bonding and Joint Thickness Impact Structural Durability',
        'slug'        => 'why-mortar-bonding-impacts-structural-durability',
        'category'    => 'Technical Masonry',
        'tags'        => 'Masonry, Mortar, Engineering',
        'image'       => 'wall.png',
        'excerpt'     => 'The science behind 1:4 and 1:6 cement-sand mortar ratios, pre-wetting bricks before laying, and maintaining uniform 3/8" bed joints.',
        'content'     => 'A brick wall is only as durable as the bond between the brick surface and the cement mortar. If dry bricks are placed directly into wet mortar, the dry porous clay rapidly siphons water out of the mix, preventing proper cement hydration and leading to powdery weak joints. Always pre-soak bricks for at least 2 hours prior to laying, maintain a strict 3/8-inch (10mm) uniform joint thickness, and cure newly laid walls with water spray for at least 7 to 10 days.',
      ),
      array(
        'title'       => 'Monsoon Construction Protection: Preventing Seepage and Dampness',
        'slug'        => 'monsoon-construction-protection-preventing-seepage',
        'category'    => 'Weatherproofing',
        'tags'        => 'Waterproofing, Monsoon, Protection',
        'image'       => 'worker.png',
        'excerpt'     => 'Essential site precautions to protect fresh concrete, sand mounds, and cement bags during heavy Punjab rainy seasons.',
        'content'     => 'Monsoon rain can degrade raw materials if site logistics are neglected. Ensure cement bags are stacked on raised wooden pallets inside weatherproof sheds at least 6 inches above ground level. Cover aggregate and sand mounds with heavy tarpaulins to avoid fine particle runoff. Incorporate polymer SBR chemical admixtures into ground-floor Damp Proof Courses (DPC) and foundation footings to permanently prevent rising damp.',
      ),
    ),
  );
}
